### ISSUE TITLE
More descriptive logging

### ISSUE THREAD

**Issue by dtcarls** [dtcarls/fantasy_football_chat_bot#112]
**Is your feature request related to a problem? Please describe.**
This generic error will be thrown for any problem with any of the webhooks

```2021-11-17T00:30:06.767794+00:00 app[worker.1]: Job "bot_main (trigger: cron[day_of_week='tue', hour='18', minute='30'], next run at: 2021-11-23 18:30:00 CST)" raised an exception
2021-11-17T00:30:06.767804+00:00 app[worker.1]: Traceback (most recent call last):
2021-11-17T00:30:06.767804+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
2021-11-17T00:30:06.767805+00:00 app[worker.1]:     retval = job.func(*job.args, **job.kwargs)
2021-11-17T00:30:06.767806+00:00 app[worker.1]:   File "/app/ff_bot/ff_bot.py", line 548, in bot_main
2021-11-17T00:30:06.767806+00:00 app[worker.1]:     discord_bot.send_message(text)
2021-11-17T00:30:06.767807+00:00 app[worker.1]:   File "/app/ff_bot/ff_bot.py", line 98, in send_message
2021-11-17T00:30:06.767807+00:00 app[worker.1]:     raise DiscordException('WEBHOOK_URL')
2021-11-17T00:30:06.767808+00:00 app[worker.1]: DiscordException: WEBHOOK_URL```

**Describe the solution you'd like**
Log actual exception thrown.

**Comment by dtcarls** [comment]
in beta testing in [develop](https://github.com/dtcarls/fantasy_football_chat_bot/tree/develop)
