### ISSUE TITLE
Can't Activate on Non-Owner GroupMe

### ISSUE THREAD

**Issue by covie92** [dtcarls/fantasy_football_chat_bot#39]
I'm in the process of activating the bot for a second GroupMe (1st works correctly)

I have gone through the steps a few times, and have included the SWID and ESPN_s2 variable; however, I am wondering if the issue is that I am not the Owner of the Groupme channel?

I was able to add the GroupMe bot to the group successfully, but it won't post the INIT message, so I don't think it's connected.

Any help is greatly appreciated!

**Comment by dtcarls** [comment]
Can you post your environment variables (minus SWID and ESPN_S2 vars for privacy reasons) and Heroku log messages?

**Comment by covie92** [comment]
BOT_ID: 7a7bff0e915f9fefdfa28d6686
DISCORD_WEBHOOK_URL: 1
END_DATE: 2019-12-30
INIT_MSG: Hi
SLACK_WEBHOOK_URL: 1
START_DATE: 2019-09-04
TIMEZONE: America/Chicago

**Build Log:**
-----> Python app detected

-----> Installing python-3.6.8

-----> Installing pip

-----> Installing SQLite3

-----> Installing requirements with pip

       Collecting flake8==3.3.0 (from -r /tmp/build_fcc1b7a318bf501081da42127d44178e/requirements.txt (line 1))

         Downloading https://files.pythonhosted.org/packages/cd/a6/1fe37679be3b224c96d8b64782d724d6a2c4212c8ddd914572fb8317a298/flake8-3.3.0-py2.py3-none-any.whl (66kB)

       Collecting apscheduler>=3.3.0 (from -r /tmp/build_fcc1b7a318bf501081da42127d44178e/requirements.txt (line 2))

         Downloading https://files.pythonhosted.org/packages/09/ff/d5b0e81846cd5e92d02e5f2682b78c73a5d9d61bc1eae32cea5ac15c0d47/APScheduler-3.6.1-py2.py3-none-any.whl (58kB)

       Collecting requests<3.0.0,>=2.0.0 (from -r /tmp/build_fcc1b7a318bf501081da42127d44178e/requirements.txt (line 3))

         Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)

       Collecting ff_espn_api>=1.1.0 (from -r /tmp/build_fcc1b7a318bf501081da42127d44178e/requirements.txt (line 4))

         Downloading https://files.pythonhosted.org/packages/b2/0a/13523d8c8a7693a2a4d9491b9c6fe00fde020be5b0441cbc7e96ae7869ce/ff_espn_api-1.1.0.tar.gz

       Collecting mccabe<0.7.0,>=0.6.0 (from flake8==3.3.0->-r /tmp/build_fcc1b7a318bf501081da42127d44178e/requirements.txt (line 1))

         Downloading https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl

       Collecting pyflakes<1.6.0,>=1.5.0 (from flake8==3.3.0->-r /tmp/build_fcc1b7a318bf501081da42127d44178e/requirements.txt (line 1))

         Downloading https://files.pythonhosted.org/packages/27/49/924098b3b85c286696f37e014475d79471ffc44509613af420645a3c12cb/pyflakes-1.5.0-py2.py3-none-any.whl (225kB)

       Collecting pycodestyle<2.4.0,>=2.0.0 (from flake8==3.3.0->-r /tmp/build_fcc1b7a318bf501081da42127d44178e/requirements.txt (line 1))

         Downloading https://files.pythonhosted.org/packages/e4/81/78fe51eb4038d1388b7217dd63770b0f428370207125047312886c923b26/pycodestyle-2.3.1-py2.py3-none-any.whl (45kB)

       Collecting pytz (from apscheduler>=3.3.0->-r /tmp/build_fcc1b7a318bf501081da42127d44178e/requirements.txt (line 2))

         Downloading https://files.pythonhosted.org/packages/87/76/46d697698a143e05f77bec5a526bf4e56a0be61d63425b68f4ba553b51f2/pytz-2019.2-py2.py3-none-any.whl (508kB)

       Collecting tzlocal>=1.2 (from apscheduler>=3.3.0->-r /tmp/build_fcc1b7a318bf501081da42127d44178e/requirements.txt (line 2))

         Downloading https://files.pythonhosted.org/packages/ef/99/53bd1ac9349262f59c1c421d8fcc2559ae8a5eeffed9202684756b648d33/tzlocal-2.0.0-py2.py3-none-any.whl

       Collecting six>=1.4.0 (from apscheduler>=3.3.0->-r /tmp/build_fcc1b7a318bf501081da42127d44178e/requirements.txt (line 2))

         Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl

       Collecting chardet<3.1.0,>=3.0.2 (from requests<3.0.0,>=2.0.0->-r /tmp/build_fcc1b7a318bf501081da42127d44178e/requirements.txt (line 3))

         Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)

       Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests<3.0.0,>=2.0.0->-r /tmp/build_fcc1b7a318bf501081da42127d44178e/requirements.txt (line 3))

         Downloading https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl (150kB)

       Collecting idna<2.9,>=2.5 (from requests<3.0.0,>=2.0.0->-r /tmp/build_fcc1b7a318bf501081da42127d44178e/requirements.txt (line 3))

         Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)

       Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.0.0->-r /tmp/build_fcc1b7a318bf501081da42127d44178e/requirements.txt (line 3))

         Downloading https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl (157kB)

       Installing collected packages: mccabe, pyflakes, pycodestyle, flake8, pytz, tzlocal, six, apscheduler, chardet, urllib3, idna, certifi, requests, ff-espn-api

         Running setup.py install for ff-espn-api: started

           Running setup.py install for ff-espn-api: finished with status 'done'

       Successfully installed apscheduler-3.6.1 certifi-2019.6.16 chardet-3.0.4 ff-espn-api-1.1.0 flake8-3.3.0 idna-2.8 mccabe-0.6.1 pycodestyle-2.3.1 pyflakes-1.5.0 pytz-2019.2 requests-2.22.0 six-1.12.0 tzlocal-2.0.0 urllib3-1.25.3

-----> Discovering process types

       Procfile declares types -> worker

-----> Compressing...

       Done: 45.3M

-----> Launching...

       Released v4

       https://tom-ff-bot2.herokuapp.com/ deployed to Heroku

**Comment by dtcarls** [comment]
You don't appear to have a leagueid?

**Comment by covie92** [comment]
Sorry about that, I do have one.

LEAGUE_ID: 338094

**Comment by dtcarls** [comment]
That league appears to be private and I didn't see you include swid or espn_s2. Also, you provided the build log, I would need to see the run time log (Heroku dashboard->your ff_bot app->More (top right)->View Logs) My guess is you'll see Permissions Denied error.

**Comment by covie92** [comment]
I omitted the SWID and ESPN_s2 values for privacy sake,  but let me know if you need them to check.

Here's the run time log after trying to restart it:


2019-09-19T19:20:44.671562+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/ff_espn_api/league.py", line 54, in __init__

2019-09-19T19:20:44.672271+00:00 app[worker.1]:     self._fetch_league()

2019-09-19T19:20:44.672318+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/ff_espn_api/league.py", line 64, in _fetch_league

2019-09-19T19:20:44.674336+00:00 app[worker.1]:     checkRequestStatus(self.status)

2019-09-19T19:20:44.674381+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/ff_espn_api/league.py", line 23, in checkRequestStatus

2019-09-19T19:20:44.675231+00:00 app[worker.1]:     raise Exception("Access Denied")

2019-09-19T19:20:44.676407+00:00 app[worker.1]: Exception: Access Denied

2019-09-19T19:33:38.645918+00:00 heroku[worker.1]: State changed from crashed to starting

2019-09-19T19:33:42.11465+00:00 heroku[worker.1]: Starting process with command `python3 ff_bot/ff_bot.py`

2019-09-19T19:33:42.844105+00:00 heroku[worker.1]: State changed from starting to up

2019-09-20T16:45:37.971589+00:00 heroku[worker.1]: Process exited with status 1

2019-09-20T16:45:38.007577+00:00 heroku[worker.1]: State changed from up to crashed

2019-09-20T16:45:38.01094+00:00 heroku[worker.1]: State changed from crashed to starting

2019-09-20T16:45:37.882658+00:00 app[worker.1]: Traceback (most recent call last):

2019-09-20T16:45:37.882697+00:00 app[worker.1]:   File "ff_bot/ff_bot.py", line 348, in <module>

2019-09-20T16:45:37.883446+00:00 app[worker.1]:     bot_main("init")

2019-09-20T16:45:37.883454+00:00 app[worker.1]:   File "ff_bot/ff_bot.py", line 283, in bot_main

2019-09-20T16:45:37.883799+00:00 app[worker.1]:     league = League(league_id, year, espn_s2, swid)

2019-09-20T16:45:37.883814+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/ff_espn_api/league.py", line 54, in __init__

2019-09-20T16:45:37.883987+00:00 app[worker.1]:     self._fetch_league()

2019-09-20T16:45:37.883989+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/ff_espn_api/league.py", line 64, in _fetch_league

2019-09-20T16:45:37.88411+00:00 app[worker.1]:     checkRequestStatus(self.status)

2019-09-20T16:45:37.884127+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/ff_espn_api/league.py", line 23, in checkRequestStatus

2019-09-20T16:45:37.884245+00:00 app[worker.1]:     raise Exception("Access Denied")

2019-09-20T16:45:37.884267+00:00 app[worker.1]: Exception: Access Denied

2019-09-20T16:45:41.393139+00:00 heroku[worker.1]: Starting process with command `python3 ff_bot/ff_bot.py`

2019-09-20T16:45:42.057728+00:00 heroku[worker.1]: State changed from starting to up

2019-09-20T16:45:43.589065+00:00 heroku[worker.1]: source=worker.1 dyno=heroku.145429057.65ba65a4-632d-4779-9106-12b268adad11 sample#memory_total=11.86MB sample#memory_rss=11.86MB sample#memory_cache=0.00MB sample#memory_swap=0.00MB sample#memory_pgpgin=3629pages sample#memory_pgpgout=593pages sample#memory_quota=512.00MB

2019-09-20T16:45:44.282717+00:00 heroku[worker.1]: Process exited with status 1

2019-09-20T16:45:44.325895+00:00 heroku[worker.1]: State changed from up to crashed

2019-09-20T16:45:44.19255+00:00 app[worker.1]: Traceback (most recent call last):

2019-09-20T16:45:44.192574+00:00 app[worker.1]:   File "ff_bot/ff_bot.py", line 348, in <module>

2019-09-20T16:45:44.193134+00:00 app[worker.1]:     bot_main("init")

2019-09-20T16:45:44.193142+00:00 app[worker.1]:   File "ff_bot/ff_bot.py", line 283, in bot_main

2019-09-20T16:45:44.193362+00:00 app[worker.1]:     league = League(league_id, year, espn_s2, swid)

2019-09-20T16:45:44.193365+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/ff_espn_api/league.py", line 54, in __init__

2019-09-20T16:45:44.193571+00:00 app[worker.1]:     self._fetch_league()

2019-09-20T16:45:44.193577+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/ff_espn_api/league.py", line 64, in _fetch_league

2019-09-20T16:45:44.193791+00:00 app[worker.1]:     checkRequestStatus(self.status)

2019-09-20T16:45:44.193798+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/ff_espn_api/league.py", line 23, in checkRequestStatus

2019-09-20T16:45:44.193977+00:00 app[worker.1]:     raise Exception("Access Denied")

2019-09-20T16:45:44.194028+00:00 app[worker.1]: Exception: Access Denied

**Comment by dtcarls** [comment]
I would double check your swid and espn_s2 are correct. You can see the repeated "Access Denied" errors. You can also make your league public for an easy fix or to verify that is in fact the issue.

**Comment by dtcarls** [comment]
Re-open if you are still having this problem
