### ISSUE TITLE
Did not receive scoreboard today at 4:00 PM ET

### ISSUE THREAD

**Issue by dyoung005** [dtcarls/fantasy_football_chat_bot#78]
I did not receive the scoreboard update today at 4:00 PM ET I am using GroupMe with a private ESPN League I have had no issues with this in the past.

**Comment by csabatini** [comment]
Same, here is the exception, got the same thing on a few attempts.

```
Traceback (most recent call last):                                                                                                                                           
	File "/usr/local/lib/python3.7/site-packages/APScheduler-3.6.3-py3.7.egg/apscheduler/executors/base.py", line 125, in run_job                                                
		retval = job.func(*job.args, **job.kwargs)                                                                                                                               
	File "ff_bot/ff_bot.py", line 314, in bot_main                                                                                                                               
		text = get_scoreboard_short(league)                                                                                                                                      
	File "ff_bot/ff_bot.py", line 112, in get_scoreboard_short                                                                                                                   
		box_scores = league.box_scores(week=week)                                                                                                                                
	File "/usr/local/lib/python3.7/site-packages/espn_api-0.8.0-py3.7.egg/espn_api/football/league.py", line 201, in box_scores                                                  
		pro_schedule = self._get_pro_schedule(week)                                                                                                                              
	File "/usr/local/lib/python3.7/site-packages/espn_api-0.8.0-py3.7.egg/espn_api/base_league.py", line 87, in _get_pro_schedule                                                
		game_data = team['proGamesByScoringPeriod'][str(scoringPeriodId)][0]                                                                                                   
IndexError: list index out of range
```

**Comment by csabatini** [comment]
I will open a separate issue since it doesn't seem directly caused by the bot

**Comment by dtcarls** [comment]
Thanks, putting link here for tracking. I'll merge the latest library once put into master.
https://github.com/cwendt94/espn-api/issues/140

**Comment by dtcarls** [comment]
Bots will need to be redeployed to take the change.
